{% set name = "pyepr-quantum" %}
{% set version = "0.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zlatko-minev/pyEPR/archive/{{ version }}.tar.gz
  sha256: 7d7954b5f026f2c6bc3e4c0fa4241cb9abcd1fad1ce9fda69ce6108f9e92b2b3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - attrdict
    - ipython >=7.0.0
    - matplotlib-base >=3.1.0
    - numpy >=1.15.0
    - pandas >=1.0.1
    - pint
    - python >=3.6
    - qutip
    - seaborn >=0.10.0
    - sphinx_rtd_theme >=0.4.0
    - scipy >=1.3.0
    - sympy >=1.3
    - xarray >=0.10.0

test:
  imports:
    - pyEPR

about:
  home: https://github.com/zlatko-minev/pyEPR
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Automated Python module for the design and quantization of Josephson quantum circuits
  doc_url: https://pyepr-docs.readthedocs.io/
  dev_url: https://github.com/zlatko-minev/pyEPR

extra:
  recipe-maintainers:
    - zlatko-minev
    - wshanks
