{% set name = "pyepr-quantum" %}
{% set version = "0.8.03" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zlatko-minev/pyEPR/archive/{{ version }}.tar.gz
  sha256: 574be90499eef9481b0c2643aa72e471215a42cbb8c3375a29afd5e0ec7b3da3

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - attrdict
    - ipython >=7.0.0
    - matplotlib-base >=3.1.0
    - numpy >=1.15.0
    - pandas >=1.0.1
    - pint
    - python
    - qutip
    - seaborn >=0.10.0
    - sphinx_rtd_theme >=0.4.0
    - scipy >=1.3.0
    - sympy >=1.3
    - xarray >=0.10.0

test:
  imports:
    - pyEPR

about:
  home: https://github.com/zlatko-minev/pyEPR
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Automated Python module for the design and quantization of Josephson quantum circuits
  doc_url: https://pyepr-docs.readthedocs.io/
  dev_url: https://github.com/zlatko-minev/pyEPR

extra:
  recipe-maintainers:
    - zlatko-minev
    - willsALMANJ
