{% set name = "pyepr-quantum" %}
{% set version = "0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1b3a3f15925a7c2158b4cae710e678a516899c83b557852f199a1d86d89e5470

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - attrdict
    - ipython >=7.0.0
    - matplotlib-base >=3.1.0
    - numpy >=1.15.0
    - pandas >=1.0.1
    - pint
    - python
    - qutip
    - seaborn >=0.10.0
    - sphinx_rtd_theme >=0.4.0
    - scipy >=1.3.0
    - sympy >=1.3
    - xarray >=0.10.0

test:
  imports:
    - pyEPR

about:
  home: https://github.com/zlatko-minev/pyEPR
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Automated Python module for the design and quantization of Josephson quantum circuits
  doc_url: https://pyepr-docs.readthedocs.io/
  dev_url: https://github.com/zlatko-minev/pyEPR

extra:
  recipe-maintainers:
    - zlatko-minev
    - wshanks
